# Generated by Django 5.1.1 on 2024-09-11 01:00

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('가볼 만한 곳', '가볼 만한 곳'), ('음식점', '음식점'), ('숙소', '숙소')], max_length=10)),
                ('description', models.CharField(max_length=4000)),
                ('location', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=15)),
                ('closed_days', models.CharField(max_length=100)),
                ('parking_facilities', models.CharField(max_length=100)),
                ('rent_stroller', models.CharField(choices=[('없음', '없음'), ('가능', '가능'), ('있음', '있음')], max_length=10)),
                ('accompany_pets', models.CharField(choices=[('없음', '없음'), ('가능', '가능'), ('있음', '있음')], max_length=10)),
                ('is_credit_card_possible', models.CharField(choices=[('없음', '없음'), ('가능', '가능'), ('있음', '있음')], max_length=10)),
                ('admission_fee', models.CharField(max_length=200)),
                ('is_restroom', models.CharField(choices=[('없음', '없음'), ('가능', '가능'), ('있음', '있음')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, editable=False, max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.image_upload_path)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeimages', to='place.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
