# Generated by Django 5.1.1 on 2024-09-16 06:59

import django.db.models.deletion
import place.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=place.models.image_upload_path),
        ),
        migrations.CreateModel(
            name='PlaceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, editable=False, max_length=10)),
                ('fingerprint', models.CharField(default='None', max_length=64)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='place.place')),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
